hash-format = "sha256"

[[files]]
file = "mods/ae2.pw.toml"
hash = "354e66b34e726f2f900ffbbd6cf52cafeb2fe31ed934bebae229a10a0359cbd1"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "1aaba088a650cc1499e1871cfa92f97e3d10a9d8c612fbd784b36c12382196de"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "0cbc4b2c6b58b7a94f030ae84f18057e5dc78a17bad429f40b8884926a6ab233"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "e1016eb125a5a41a10f80847eb00affae0e539e703846f303949ed5d82b7f1bf"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "4eb0979fd7cada4b6e3dd3fec8ced79ee0892e2b7ffba6466430387cd520acee"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/ars-energistique.pw.toml"
hash = "7ce1bd971a8571077ffc4d7625e411c2a35a8d02791392a0efef8270c18359e3"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "705856841852ca6823fb2b16c7e82c15ce251bf995ac6ac725ee5665d3b54dd1"
metafile = true

[[files]]
file = "mods/arsdelight.pw.toml"
hash = "710e7c2423c8a14f2037f88e955544ad55d54460a1f2e5b884b34d60aa1cb0b1"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7eb6b5ee57865d6221be3c428f5a0c4e449f4c86920e9f8736b4f755d7822edf"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "58396d4cd2dee0f75cf56def0ab301021b6e09a83bd2564212152f0a73433568"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "33fbfba45630792a9223d4e20c9300bc9fef142c68781fc648c32b62313f3e16"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "cd158052ad85da0c90c9613564f10999ca6c26fe527b77355686d22bdcca100e"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "0e17f9758f6f67ef87aa6f8d5afc47901521a05904cd8470ef65063b48e69d73"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0bdcf1c5057873c78db71bee196ccf5ec846f6cf82f639b094668b3ba92e151f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "903352ffbd84d4b95fed905893f4715d9c3f88ec9fff6fb06f6e359e0b839dc3"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "a2c5d820180d2610e5017e3f08957010e30cf05d50ee3180272dac6f969260cf"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "852ee3d5dea735c0c8f4c030edb06164863e7d27eef535c697f86a8b20a1cff0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "b2c7739b56ef71f50a86658cfa67375796beafd391c4dbe26a5de8cd92b9b685"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "5cf8a06431f16a18dc468baae3fbdf17cc1d72b9697da58cb126342ed937aa59"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "7c1ac01f8026fac8630fa7762a4325bfda54578d7904890904308b921d33ebd8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a4c814876cd9046f9cdbe0a5967edff092adb8c28de2d717ce5fe469d6fbc9a2"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "e7bbad3e030af9a9d0bbc35f62ede52fff316f8bc2d67f86853a9ab338065e07"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "84e6ec23b1d9e88d4e1147d3d3c7c50b387f4b7ce06c52d3d8b6ceb6412907ee"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b597014c87e5dba13a0c5942456e07588a7a1c806f83016dd18be4ae4046fcf4"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "52b91a35eb2f22e4e710e2e42fe34a6a4785aefa9214fcf40da3c8e6bfa6dd44"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "ce198cf0e4ac56f35c03b5e721eacbd6c6bc86b6ab318c4c7259082edb625fc2"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/fixescape.pw.toml"
hash = "fd122c3e38c38f7a24e3d49f36dacf6cc971d969687d3d5cb6a5a61e24c13bc7"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "a66ce8fdd15abadd17b5d3d62e5bca0afe8209c081c8be1407b0e6166c8714d9"
metafile = true

[[files]]
file = "mods/gjeb.pw.toml"
hash = "4efbed1c99a588473a4471db49d7186f15172cf18e9da6ba8828609fd0357d3a"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "df07d5af0d287b944943b65e0b0990dc21fbbad6fee05b9d698a9f62b906ea9c"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "2514cf5b79023dea4f80446a03bfef5ddfaa4cc3a463abb49fd8a16c891ac620"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6d8ca5f4586ae60fe0771ae32a7cb3230030b92fda58d1761c770c24afaa54b2"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "5ce73cea812cb66372354398608d37b8fefd45db242e2aced03fbde5598df311"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "5a98133891a72e041e37bc235e86d495e488387f1628fc1377e6b5169dfbb8bd"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "47b9410704efc0f8cb3b34a87d7019a013850775afe464e887b19ecf45eac0d3"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "adb67ada5c165ea4a43f4c3e53ffd61c90e21292596b5609d97e938f6e8e7b16"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f7f82c3216ba9bfac7b9d040d0a1845d94f693b70f9981f5caf497e81f73bfae"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "1e3a1a97caff0bce36a008aeb2131dfdccbdf182b4f115d284f2297046a9e379"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c18dd089c44103b56f8edcbd41a071e41a1fcd46094b2c93df5cc5f07853f18b"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "7cb67085fb4e3ff71f09a36df813e4da8d02d7ce4623e6f6ede2df412ade621f"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "8cfbfe1fc2347a2fcaefbda03cc1b4672f985895dc6b2c8dcab54f02f75c566f"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "765987a78e5d8c782d0da2de99998b43b5907d6c41347d3804045ad109e4a586"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "d668582ea913944b31fda3e0cbe8bd7fda3852f960bd4f7a58fe9bba526a9037"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/serene-shrubbery.pw.toml"
hash = "26a8e7da021b12b227cdacac756ac1690670f4dbe1948d174aced7c40070aa73"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "8fed76ae3ed08f943570023892eb4680990198ca37ec8b24232b6237d8f7be29"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "d0bb9d21bf0da0429bf9bf01bf7a5201f8ec9ff0d6b1334fe267ed847aea5c7c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "416bb6449da951ec1a04156348c502b9e47a947212becc173d277faaddaaaccd"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/stellarview.pw.toml"
hash = "fa911350e43b1503efb9bb35f4ce9c31d69a1d2b3de71bede3a52cfd2b8cd685"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "72b2c23a2e9ca7ca0046bf1518851b4d409b489e8adac33d34651eddfc332604"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "6160cdcd8b686e90f72e76072ba96de7c5ae40460b3771401222ddebdee1d5ed"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "131c818cca79586fdca0535062a63581e7c438efd108be4403ab8faea92e6368"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "72c0e1d4d8eb05e6c82c8959885ee5f08b8c7ede63b438e22a7422246679cc46"
metafile = true

[[files]]
file = "mods/travelers-titles.pw.toml"
hash = "16e2c84951ba32efac8703ccb7b36631b70cb514d402fa8fb4f89031f2a63a58"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "073176bf34feab44656497b2e5ddf80eae8cf12f743f332d56ac0544bd91d8e2"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c557d1b26559ef987c229187d2f2705616e78179ce04fa1c96cc3d76a1cdf1b5"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "de4b3b898a16ed4d615cfce18ac872e6a963605d52072d290b495cdff160a34c"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "bbec88a5550466b7303b26f32ac82e471474697b590980822b06c6967d418d15"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "152c6732da180e958fb29f492bae2e468d4dfd423ce4d3d0d31ef31c2eec6c61"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "532f07775974b695733981b2548859d3bc76c743781a5da5035d40fd6e485ab0"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "c35112cced2eec8e5782c5c4327ae31bce16cc1356c75e52000053e890e0f0c1"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "302d69d833264022aa7ff781dbcde7f60f3c9e3021881b29f6f59223c36579c8"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "8c8b596c0e8f7366e30ee6edbd591fba9ef16741c25a505e64de9a299cd72e80"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "41aa01e9d0507d3131eb5fd2f6d8f2b7c54237e30a94e2a3bf6f52915cb8a688"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "05f825a655bc94af6ab592d13c396b60c818cfc65ff2528e206e7a40a180e210"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "60511ad5628ed8e45a552de171c3330bdcdbd5f86f7047e26b505b7a8c824a47"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "18dfe8ada0af83eb86d4b8ff8e202479b7c2ab1ee1f894d9bb07cda1744e8981"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "e25c97f72666319efdd79eafc22301376446912cbb8ac14339c428c98e3ce1b5"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "f759c09a8fef97038be0c9daaee09e5252a3ddaf56870cabc9af11e5fced97d4"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
