name = "johnpack"
author = "gunbux"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9da3ec09bb9c730abb300704dc27424c7c57159be36bae1897dd2654bb5f706"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
