name = "johnpack"
author = "gunbux"
version = "0.0.4-dcintegration"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19f0e6ff85da75f38737d0a7ade709b6b317bbcb4e5d6d8e0796d746d4b814d2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
