name = "johnpack"
author = "gunbux"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da0634aa428b8ff707dc97c841fb2cea9f168b3110ed1d9a93501aefc9a862b0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
